

<!DOCTYPE html>
<html class="writer-html5" lang="en" data-content_root="./">
<head>
  <meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>BuildSketch &mdash; build123d 0.9.2.dev40+gb1f0eed documentation</title>
      <link rel="stylesheet" type="text/css" href="_static/pygments.css?v=b86133f3" />
      <link rel="stylesheet" type="text/css" href="_static/css/theme.css?v=e59714d7" />
      <link rel="stylesheet" type="text/css" href="_static/graphviz.css?v=4ae1632d" />
      <link rel="stylesheet" type="text/css" href="_static/copybutton.css?v=76b2166b" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster.custom.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster.bundle.min.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster-sideTip-shadow.min.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster-sideTip-punk.min.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster-sideTip-noir.min.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster-sideTip-light.min.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster-sideTip-borderless.min.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/micromodal.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/sphinx_rtd_theme.css?v=3234e928" />
      <link rel="stylesheet" type="text/css" href="_static/sphinx-design.min.css?v=95c83b7e" />

  
      <script src="_static/jquery.js?v=5d32c60e"></script>
      <script src="_static/_sphinx_javascript_frameworks_compat.js?v=2cd50e6c"></script>
      <script src="_static/documentation_options.js?v=c97902b4"></script>
      <script src="_static/doctools.js?v=9bcbadda"></script>
      <script src="_static/sphinx_highlight.js?v=dc90522c"></script>
      <script src="_static/clipboard.min.js?v=a7894cd8"></script>
      <script src="_static/copybutton.js?v=f281be69"></script>
      <script src="_static/js/hoverxref.js"></script>
      <script src="_static/js/tooltipster.bundle.min.js"></script>
      <script src="_static/js/micromodal.min.js"></script>
      <script src="_static/design-tabs.js?v=f930bc37"></script>
      <script async="async" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <script src="_static/js/theme.js"></script>
    <link rel="index" title="Index" href="genindex.html" />
    <link rel="search" title="Search" href="search.html" />
    <link rel="next" title="BuildPart" href="build_part.html" />
    <link rel="prev" title="BuildLine" href="build_line.html" /> 
</head>

<body class="wy-body-for-nav"> 
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >

          
          
          <a href="index.html" class="icon icon-home">
            build123d
              <img src="_static/logo.svg" class="logo" alt="Logo"/>
          </a>
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" aria-label="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>
        </div><div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
              <ul class="current">
<li class="toctree-l1"><a class="reference internal" href="introduction.html">Introduction</a></li>
<li class="toctree-l1"><a class="reference internal" href="installation.html">Installation</a></li>
<li class="toctree-l1"><a class="reference internal" href="key_concepts.html">Key Concepts</a></li>
<li class="toctree-l1"><a class="reference internal" href="key_concepts_builder.html">Key Concepts (builder mode)</a></li>
<li class="toctree-l1"><a class="reference internal" href="key_concepts_algebra.html">Key Concepts (algebra mode)</a></li>
<li class="toctree-l1"><a class="reference internal" href="moving_objects.html">Moving Objects</a></li>
<li class="toctree-l1"><a class="reference internal" href="OpenSCAD.html">Transitioning from OpenSCAD</a></li>
<li class="toctree-l1"><a class="reference internal" href="introductory_examples.html">Introductory Examples</a></li>
<li class="toctree-l1"><a class="reference internal" href="tutorials.html">Tutorials</a></li>
<li class="toctree-l1"><a class="reference internal" href="objects.html">Objects</a></li>
<li class="toctree-l1"><a class="reference internal" href="selectors_operators.html">Selectors and Operators</a></li>
<li class="toctree-l1"><a class="reference internal" href="operations.html">Operations</a></li>
<li class="toctree-l1 current"><a class="reference internal" href="builders.html">Builders</a><ul class="current">
<li class="toctree-l2"><a class="reference internal" href="build_line.html">BuildLine</a></li>
<li class="toctree-l2 current"><a class="current reference internal" href="#">BuildSketch</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#basic-functionality">Basic Functionality</a></li>
<li class="toctree-l3"><a class="reference internal" href="#sketching-on-other-planes">Sketching on other Planes</a></li>
<li class="toctree-l3"><a class="reference internal" href="#local-vs-global-sketches">Local vs. Global Sketches</a></li>
<li class="toctree-l3"><a class="reference internal" href="#locating-features">Locating Features</a></li>
<li class="toctree-l3"><a class="reference internal" href="#module-build_sketch">Reference</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#build_sketch.BuildSketch"><code class="docutils literal notranslate"><span class="pre">BuildSketch</span></code></a></li>
</ul>
</li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="build_part.html">BuildPart</a></li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="joints.html">Joints</a></li>
<li class="toctree-l1"><a class="reference internal" href="assemblies.html">Assemblies</a></li>
<li class="toctree-l1"><a class="reference internal" href="tips.html">Tips, Best Practices and FAQ</a></li>
<li class="toctree-l1"><a class="reference internal" href="import_export.html">Import/Export</a></li>
<li class="toctree-l1"><a class="reference internal" href="advanced.html">Advanced Topics</a></li>
<li class="toctree-l1"><a class="reference internal" href="cheat_sheet.html">Cheat Sheet</a></li>
<li class="toctree-l1"><a class="reference internal" href="external.html">External Tools and Libraries</a></li>
<li class="toctree-l1"><a class="reference internal" href="builder_api_reference.html">Builder Common API Reference</a></li>
<li class="toctree-l1"><a class="reference internal" href="direct_api_reference.html">Direct API Reference</a></li>
</ul>

        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap"><nav class="wy-nav-top" aria-label="Mobile navigation menu" >
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="index.html">build123d</a>
      </nav>

      <div class="wy-nav-content">
        <div class="rst-content">
          <div role="navigation" aria-label="Page navigation">
  <ul class="wy-breadcrumbs">
      <li><a href="index.html" class="icon icon-home" aria-label="Home"></a></li>
          <li class="breadcrumb-item"><a href="builders.html">Builders</a></li>
      <li class="breadcrumb-item active">BuildSketch</li>
      <li class="wy-breadcrumbs-aside">
            <a href="_sources/build_sketch.rst.txt" rel="nofollow"> View page source</a>
      </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
             
  <section id="buildsketch">
<h1>BuildSketch<a class="headerlink" href="#buildsketch" title="Link to this heading"></a></h1>
<p>BuildSketch is a python context manager that is used to create planar two dimensional
objects - objects with the property of area but not volume - that are typically
used as profiles for BuildPart operations like <a class="hxr-hoverxref hxr-tooltip reference internal" href="operations.html#operations_part.extrude" title="operations_part.extrude"><code class="xref py py-func docutils literal notranslate"><span class="pre">extrude()</span></code></a> or
<a class="hxr-hoverxref hxr-tooltip reference internal" href="operations.html#operations_part.revolve" title="operations_part.revolve"><code class="xref py py-func docutils literal notranslate"><span class="pre">revolve()</span></code></a>.</p>
<p>The complete API for BuildSketch is located at the end of this section.</p>
<section id="basic-functionality">
<h2>Basic Functionality<a class="headerlink" href="#basic-functionality" title="Link to this heading"></a></h2>
<p>The following is a simple BuildSketch example:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="n">length</span><span class="p">,</span> <span class="n">radius</span> <span class="o">=</span> <span class="mf">40.0</span><span class="p">,</span> <span class="mf">60.0</span>

<span class="k">with</span> <span class="n">BuildSketch</span><span class="p">()</span> <span class="k">as</span> <span class="n">circle_with_hole</span><span class="p">:</span>
    <span class="n">Circle</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="n">radius</span><span class="p">)</span>
    <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">length</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">length</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">)</span>
</pre></div>
</div>
<p>The <code class="docutils literal notranslate"><span class="pre">with</span></code> statement creates the <code class="docutils literal notranslate"><span class="pre">BuildSketch</span></code> context manager with the
identifier <code class="docutils literal notranslate"><span class="pre">circle_with_hole</span></code>. The objects and operations that are within the
scope (i.e. indented) of this context will contribute towards the object
being created by the context manager.  For <code class="docutils literal notranslate"><span class="pre">BuildSketch</span></code>, this object is
<code class="docutils literal notranslate"><span class="pre">sketch</span></code> and it’s referenced as <code class="docutils literal notranslate"><span class="pre">circle_with_hole.sketch</span></code>.</p>
<p>The first object in this example is a <code class="docutils literal notranslate"><span class="pre">Circle</span></code> object which is used to create
a filled circular shape on the default XY plane. The second object is a <code class="docutils literal notranslate"><span class="pre">Rectangle</span></code>
that is subtracted from the circle as directed by the <code class="docutils literal notranslate"><span class="pre">mode=Mode.SUBTRACT</span></code> parameter.
A key aspect of sketch objects is that they are all filled shapes and not just
a shape perimeter which enables combining subsequent shapes with different modes
(the valid values of Mode are <code class="docutils literal notranslate"><span class="pre">ADD</span></code>, <code class="docutils literal notranslate"><span class="pre">SUBTRACT</span></code>, <code class="docutils literal notranslate"><span class="pre">INTERSECT</span></code>, <code class="docutils literal notranslate"><span class="pre">REPLACE</span></code>,
and <code class="docutils literal notranslate"><span class="pre">PRIVATE</span></code>).</p>
<img alt="_images/circle_with_hole.svg" class="align-center" src="_images/circle_with_hole.svg" />
</section>
<section id="sketching-on-other-planes">
<span id="id1"></span><h2>Sketching on other Planes<a class="headerlink" href="#sketching-on-other-planes" title="Link to this heading"></a></h2>
<p>Often when designing parts one needs to build on top of other features.  To facilitate
doing this <code class="docutils literal notranslate"><span class="pre">BuildSketch</span></code> allows one to create sketches on any Plane while allowing
the designer to work in a local X, Y coordinate system. It might be helpful to think
of what is happening with this metaphor:</p>
<ol class="arabic simple">
<li><p>When instantiating <code class="docutils literal notranslate"><span class="pre">BuildSketch</span></code> one or more workplanes can be passed as parameters.
These are the placement targets for the completed sketch.</p></li>
<li><p>The designer draws on a flat “drafting table” which is <code class="docutils literal notranslate"><span class="pre">Plane.XY</span></code>.</p></li>
<li><p>Once the sketch is complete, it’s applied like a sticker to all of the workplanes
passed in step 1.</p></li>
</ol>
<p>As an example, let’s build the following simple control box with a display on an angled plane:</p>
<img alt="_images/controller.svg" class="align-center" src="_images/controller.svg" />
<p>Here is the code:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">controller</span><span class="p">:</span>
    <span class="c1"># Create the side view of the controller</span>
    <span class="k">with</span> <span class="n">BuildSketch</span><span class="p">(</span><span class="n">Plane</span><span class="o">.</span><span class="n">YZ</span><span class="p">)</span> <span class="k">as</span> <span class="n">profile</span><span class="p">:</span>
        <span class="k">with</span> <span class="n">BuildLine</span><span class="p">():</span>
            <span class="n">Polyline</span><span class="p">((</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">),</span> <span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">40</span><span class="p">),</span> <span class="p">(</span><span class="mi">20</span><span class="p">,</span> <span class="mi">80</span><span class="p">),</span> <span class="p">(</span><span class="mi">40</span><span class="p">,</span> <span class="mi">80</span><span class="p">),</span> <span class="p">(</span><span class="mi">40</span><span class="p">,</span> <span class="mi">0</span><span class="p">),</span> <span class="p">(</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">))</span>
        <span class="c1"># Create a filled face from the perimeter drawing</span>
        <span class="n">make_face</span><span class="p">()</span>
    <span class="c1"># Extrude to create the basis controller shape</span>
    <span class="n">extrude</span><span class="p">(</span><span class="n">amount</span><span class="o">=</span><span class="mi">30</span><span class="p">,</span> <span class="n">both</span><span class="o">=</span><span class="kc">True</span><span class="p">)</span>
    <span class="c1"># Round off all the edges</span>
    <span class="n">fillet</span><span class="p">(</span><span class="n">controller</span><span class="o">.</span><span class="n">edges</span><span class="p">(),</span> <span class="n">radius</span><span class="o">=</span><span class="mi">3</span><span class="p">)</span>
    <span class="c1"># Hollow out the controller</span>
    <span class="n">offset</span><span class="p">(</span><span class="n">amount</span><span class="o">=-</span><span class="mi">1</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">)</span>
<span class="hll">    <span class="c1"># Extract the face that will house the display</span>
</span><span class="hll">    <span class="n">display_face</span> <span class="o">=</span> <span class="p">(</span>
</span><span class="hll">        <span class="n">controller</span><span class="o">.</span><span class="n">faces</span><span class="p">()</span>
</span><span class="hll">        <span class="o">.</span><span class="n">filter_by</span><span class="p">(</span><span class="n">GeomType</span><span class="o">.</span><span class="n">PLANE</span><span class="p">)</span>
</span><span class="hll">        <span class="o">.</span><span class="n">filter_by_position</span><span class="p">(</span><span class="n">Axis</span><span class="o">.</span><span class="n">Z</span><span class="p">,</span> <span class="mi">50</span><span class="p">,</span> <span class="mi">70</span><span class="p">)[</span><span class="mi">0</span><span class="p">]</span>
</span><span class="hll">    <span class="p">)</span>
</span><span class="hll">    <span class="c1"># Create a workplane from the face</span>
</span><span class="hll">    <span class="n">display_workplane</span> <span class="o">=</span> <span class="n">Plane</span><span class="p">(</span>
</span><span class="hll">        <span class="n">origin</span><span class="o">=</span><span class="n">display_face</span><span class="o">.</span><span class="n">center</span><span class="p">(),</span> <span class="n">x_dir</span><span class="o">=</span><span class="p">(</span><span class="mi">1</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">),</span> <span class="n">z_dir</span><span class="o">=</span><span class="n">display_face</span><span class="o">.</span><span class="n">normal_at</span><span class="p">()</span>
</span><span class="hll">    <span class="p">)</span>
</span><span class="hll">    <span class="c1"># Place the sketch directly on the controller</span>
</span><span class="hll">    <span class="k">with</span> <span class="n">BuildSketch</span><span class="p">(</span><span class="n">display_workplane</span><span class="p">)</span> <span class="k">as</span> <span class="n">display</span><span class="p">:</span>
</span>        <span class="n">RectangleRounded</span><span class="p">(</span><span class="mi">40</span><span class="p">,</span> <span class="mi">30</span><span class="p">,</span> <span class="mi">2</span><span class="p">)</span>
        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span><span class="mi">45</span><span class="p">,</span> <span class="mi">35</span><span class="p">,</span> <span class="mi">2</span><span class="p">,</span> <span class="mi">2</span><span class="p">):</span>
            <span class="n">Circle</span><span class="p">(</span><span class="mi">1</span><span class="p">)</span>
    <span class="c1"># Cut the display sketch through the controller</span>
    <span class="n">extrude</span><span class="p">(</span><span class="n">amount</span><span class="o">=-</span><span class="mi">1</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">)</span>
</pre></div>
</div>
<p>The highlighted part of the code shows how a face is extracted from the design,
a workplane is constructed from this face and finally this workplane is passed
to <code class="docutils literal notranslate"><span class="pre">BuildSketch</span></code> as the target for the complete sketch.  Notice how the
<code class="docutils literal notranslate"><span class="pre">display</span></code> sketch uses local coordinates for its features thus avoiding having
the user to determine how to move and rotate the sketch to get it where it
should go.</p>
<p>Note that <code class="docutils literal notranslate"><span class="pre">BuildSketch</span></code> accepts a sequence planes, faces and locations for
workplanes so creation of an explicit workplane is often not required. Being
able to work on multiple workplanes at once allows for features to be created
on multiple side of an object - say both the top and bottom - which is convenient
for symmetric parts.</p>
</section>
<section id="local-vs-global-sketches">
<h2>Local vs. Global Sketches<a class="headerlink" href="#local-vs-global-sketches" title="Link to this heading"></a></h2>
<p>In the above example the target for the sketch was not <code class="docutils literal notranslate"><span class="pre">Plane.XY</span></code> but a workplane
passed by the user.  Internally <code class="docutils literal notranslate"><span class="pre">BuildSketch</span></code> is always creating the sketch
on <code class="docutils literal notranslate"><span class="pre">Plane.XY</span></code> which one can see by looking at the <code class="docutils literal notranslate"><span class="pre">sketch_local</span></code> property of your
sketch.  For example, to display the local version of the <code class="docutils literal notranslate"><span class="pre">display</span></code> sketch from
above, one would use:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="n">show_object</span><span class="p">(</span><span class="n">display</span><span class="o">.</span><span class="n">sketch_local</span><span class="p">,</span> <span class="n">name</span><span class="o">=</span><span class="s2">&quot;sketch on Plane.XY&quot;</span><span class="p">)</span>
</pre></div>
</div>
<p>while the sketches as applied to their target workplanes is accessible through
the <code class="docutils literal notranslate"><span class="pre">sketch</span></code> property, as follows:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="n">show_object</span><span class="p">(</span><span class="n">display</span><span class="o">.</span><span class="n">sketch</span><span class="p">,</span> <span class="n">name</span><span class="o">=</span><span class="s2">&quot;sketch on target workplane(s)&quot;</span><span class="p">)</span>
</pre></div>
</div>
<p>When using the <a class="hxr-hoverxref hxr-tooltip reference internal" href="operations.html#operations_generic.add" title="operations_generic.add"><code class="xref py py-func docutils literal notranslate"><span class="pre">add()</span></code></a> operation to add an external Face
to a sketch the face will automatically be reoriented to <code class="docutils literal notranslate"><span class="pre">Plane.XY</span></code> before being
combined with the sketch.  As Faces don’t provide an x-direction it’s possible
that the new Face may not be oriented as expected. To reorient the Face manually
to <code class="docutils literal notranslate"><span class="pre">Plane.XY</span></code> one can use the <code class="xref py py-meth docutils literal notranslate"><span class="pre">to_local_coords()</span></code> method as
follows:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="n">reoriented_face</span> <span class="o">=</span> <span class="n">plane</span><span class="o">.</span><span class="n">to_local_coords</span><span class="p">(</span><span class="n">face</span><span class="p">)</span>
</pre></div>
</div>
<p>where <code class="docutils literal notranslate"><span class="pre">plane</span></code> is the plane that <code class="docutils literal notranslate"><span class="pre">face</span></code> was constructed on.</p>
</section>
<section id="locating-features">
<h2>Locating Features<a class="headerlink" href="#locating-features" title="Link to this heading"></a></h2>
<p>Within a sketch features are positioned with <code class="docutils literal notranslate"><span class="pre">Locations</span></code> contexts
(see <a class="reference internal" href="key_concepts_builder.html#location-context-link"><span class="std std-ref">Location Context</span></a>) on the current workplane(s). The following
location contexts are available within a sketch:</p>
<ul class="simple">
<li><p><a class="hxr-hoverxref hxr-tooltip reference internal" href="builder_api_reference.html#build_common.GridLocations" title="build_common.GridLocations"><code class="xref py py-class docutils literal notranslate"><span class="pre">GridLocations</span></code></a> : a X/Y grid of locations</p></li>
<li><p><a class="hxr-hoverxref hxr-tooltip reference internal" href="builder_api_reference.html#build_common.HexLocations" title="build_common.HexLocations"><code class="xref py py-class docutils literal notranslate"><span class="pre">HexLocations</span></code></a> : a hex grid of locations ideal for nesting circles</p></li>
<li><p><a class="hxr-hoverxref hxr-tooltip reference internal" href="builder_api_reference.html#build_common.Locations" title="build_common.Locations"><code class="xref py py-class docutils literal notranslate"><span class="pre">Locations</span></code></a> : a sequence of arbitrary locations</p></li>
<li><p><a class="hxr-hoverxref hxr-tooltip reference internal" href="builder_api_reference.html#build_common.PolarLocations" title="build_common.PolarLocations"><code class="xref py py-class docutils literal notranslate"><span class="pre">PolarLocations</span></code></a> : locations defined by radius and angle</p></li>
</ul>
<p>Generally one would specify tuples of (X, Y) values when defining locations but
there are many options available to the user.</p>
</section>
<section id="module-build_sketch">
<span id="reference"></span><h2>Reference<a class="headerlink" href="#module-build_sketch" title="Link to this heading"></a></h2>
<dl class="py class">
<dt class="sig sig-object py" id="build_sketch.BuildSketch">
<em class="property"><span class="pre">class</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">BuildSketch</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="n"><span class="pre">*workplanes:</span> <span class="pre">~build123d.topology.two_d.Face</span> <span class="pre">|</span> <span class="pre">~build123d.geometry.Plane</span> <span class="pre">|</span> <span class="pre">~build123d.geometry.Location</span></span></em>, <em class="sig-param"><span class="n"><span class="pre">mode:</span> <span class="pre">~build123d.build_enums.Mode</span> <span class="pre">=</span> <span class="pre">&lt;Mode.ADD&gt;</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="_modules/build_sketch.html#BuildSketch"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#build_sketch.BuildSketch" title="Link to this definition"></a></dt>
<dd><p>The BuildSketch class is a subclass of Builder for building planar 2D
sketches (objects with area but not volume) from faces or lines.
It has an _obj property that returns the current sketch being built.
The sketch property consists of the sketch(es) applied to the input
workplanes while the sketch_local attribute is the sketch constructed
on Plane.XY. The class overrides the solids method of Builder since
they don’t apply to lines.</p>
<p>Note that all sketch construction is done within sketch_local on Plane.XY.
When objects are added to the sketch they must be coplanar to Plane.XY,
usually handled automatically but may need user input for Edges and Wires
since their construction plane isn’t always able to be determined.</p>
<dl class="field-list simple">
<dt class="field-odd">Parameters<span class="colon">:</span></dt>
<dd class="field-odd"><ul class="simple">
<li><p><strong>workplanes</strong> (<em>Union</em><em>[</em><a class="hxr-hoverxref hxr-tooltip reference internal" href="direct_api_reference.html#topology.Face" title="topology.Face"><em>Face</em></a><em>, </em><a class="hxr-hoverxref hxr-tooltip reference internal" href="direct_api_reference.html#geometry.Plane" title="geometry.Plane"><em>Plane</em></a><em>, </em><a class="hxr-hoverxref hxr-tooltip reference internal" href="direct_api_reference.html#geometry.Location" title="geometry.Location"><em>Location</em></a><em>]</em><em>, </em><em>optional</em>) – objects converted to
plane(s) to place the sketch on. Defaults to Plane.XY.</p></li>
<li><p><strong>mode</strong> (<a class="hxr-hoverxref hxr-tooltip reference internal" href="builder_api_reference.html#build_enums.Mode" title="build_enums.Mode"><em>Mode</em></a><em>, </em><em>optional</em>) – combination mode. Defaults to Mode.ADD.</p></li>
</ul>
</dd>
</dl>
<dl class="py method">
<dt class="sig sig-object py" id="build_sketch.BuildSketch.consolidate_edges">
<span class="sig-name descname"><span class="pre">consolidate_edges</span></span><span class="sig-paren">(</span><span class="sig-paren">)</span> <span class="sig-return"><span class="sig-return-icon">&#x2192;</span> <span class="sig-return-typehint"><span class="pre">Wire</span><span class="w"> </span><span class="p"><span class="pre">|</span></span><span class="w"> </span><span class="pre">list</span><span class="p"><span class="pre">[</span></span><span class="pre">Wire</span><span class="p"><span class="pre">]</span></span></span></span><a class="reference internal" href="_modules/build_sketch.html#BuildSketch.consolidate_edges"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#build_sketch.BuildSketch.consolidate_edges" title="Link to this definition"></a></dt>
<dd><p>Unify pending edges into one or more Wires</p>
</dd></dl>

<dl class="py property">
<dt class="sig sig-object py" id="build_sketch.BuildSketch.sketch">
<em class="property"><span class="pre">property</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">sketch</span></span><a class="headerlink" href="#build_sketch.BuildSketch.sketch" title="Link to this definition"></a></dt>
<dd><p>The global version of the sketch - may contain multiple sketches</p>
</dd></dl>

<dl class="py property">
<dt class="sig sig-object py" id="build_sketch.BuildSketch.sketch_local">
<em class="property"><span class="pre">property</span><span class="w"> </span></em><span class="sig-name descname"><span class="pre">sketch_local</span></span><em class="property"><span class="p"><span class="pre">:</span></span><span class="w"> </span><span class="pre">Sketch</span><span class="w"> </span><span class="p"><span class="pre">|</span></span><span class="w"> </span><span class="pre">None</span></em><a class="headerlink" href="#build_sketch.BuildSketch.sketch_local" title="Link to this definition"></a></dt>
<dd><p>Get the builder’s object</p>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="build_sketch.BuildSketch.solid">
<span class="sig-name descname"><span class="pre">solid</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="o"><span class="pre">*</span></span><span class="n"><span class="pre">args</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="_modules/build_sketch.html#BuildSketch.solid"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#build_sketch.BuildSketch.solid" title="Link to this definition"></a></dt>
<dd><p>solid() not implemented</p>
</dd></dl>

<dl class="py method">
<dt class="sig sig-object py" id="build_sketch.BuildSketch.solids">
<span class="sig-name descname"><span class="pre">solids</span></span><span class="sig-paren">(</span><em class="sig-param"><span class="o"><span class="pre">*</span></span><span class="n"><span class="pre">args</span></span></em><span class="sig-paren">)</span><a class="reference internal" href="_modules/build_sketch.html#BuildSketch.solids"><span class="viewcode-link"><span class="pre">[source]</span></span></a><a class="headerlink" href="#build_sketch.BuildSketch.solids" title="Link to this definition"></a></dt>
<dd><p>solids() not implemented</p>
</dd></dl>

</dd></dl>

</section>
</section>


           </div>
          </div>
          <footer><div class="rst-footer-buttons" role="navigation" aria-label="Footer">
        <a href="build_line.html" class="btn btn-neutral float-left" title="BuildLine" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left" aria-hidden="true"></span> Previous</a>
        <a href="build_part.html" class="btn btn-neutral float-right" title="BuildPart" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right" aria-hidden="true"></span></a>
    </div>

  <hr/>

  <div role="contentinfo">
    <p>&#169; Copyright 2022, Gumyr.</p>
  </div>

  Built with <a href="https://www.sphinx-doc.org/">Sphinx</a> using a
    <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a>
    provided by <a href="https://readthedocs.org">Read the Docs</a>.
   

</footer>
        </div>
      </div>
    </section>
  </div>
  <script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>