

<!DOCTYPE html>
<html class="writer-html5" lang="en" data-content_root="./">
<head>
  <meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Lego Tutorial &mdash; build123d 0.9.2.dev40+gb1f0eed documentation</title>
      <link rel="stylesheet" type="text/css" href="_static/pygments.css?v=b86133f3" />
      <link rel="stylesheet" type="text/css" href="_static/css/theme.css?v=e59714d7" />
      <link rel="stylesheet" type="text/css" href="_static/graphviz.css?v=4ae1632d" />
      <link rel="stylesheet" type="text/css" href="_static/copybutton.css?v=76b2166b" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster.custom.css?v=7bc2f056" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster.bundle.min.css?v=37217874" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster-sideTip-shadow.min.css?v=6227e517" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster-sideTip-punk.min.css?v=94669e23" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster-sideTip-noir.min.css?v=21a39f42" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster-sideTip-light.min.css?v=a18b2449" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster-sideTip-borderless.min.css?v=dbff53e4" />
      <link rel="stylesheet" type="text/css" href="_static/css/micromodal.css?v=d7bf34ee" />
      <link rel="stylesheet" type="text/css" href="_static/css/sphinx_rtd_theme.css?v=3234e928" />
      <link rel="stylesheet" type="text/css" href="_static/sphinx-design.min.css?v=95c83b7e" />

  
      <script src="_static/jquery.js?v=5d32c60e"></script>
      <script src="_static/_sphinx_javascript_frameworks_compat.js?v=2cd50e6c"></script>
      <script src="_static/documentation_options.js?v=c97902b4"></script>
      <script src="_static/doctools.js?v=9bcbadda"></script>
      <script src="_static/sphinx_highlight.js?v=dc90522c"></script>
      <script src="_static/clipboard.min.js?v=a7894cd8"></script>
      <script src="_static/copybutton.js?v=f281be69"></script>
      <script src="_static/js/hoverxref.js?v=6ff7264e"></script>
      <script src="_static/js/tooltipster.bundle.min.js?v=18bf091b"></script>
      <script src="_static/js/micromodal.min.js?v=04d6302d"></script>
      <script src="_static/design-tabs.js?v=f930bc37"></script>
      <script async="async" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <script src="_static/js/theme.js"></script>
    <link rel="index" title="Index" href="genindex.html" />
    <link rel="search" title="Search" href="search.html" />
    <link rel="next" title="Joint Tutorial" href="tutorial_joints.html" />
    <link rel="prev" title="Selector Tutorial" href="tutorial_selectors.html" /> 
</head>

<body class="wy-body-for-nav"> 
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >

          
          
          <a href="index.html" class="icon icon-home">
            build123d
              <img src="_static/logo.svg" class="logo" alt="Logo"/>
          </a>
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" aria-label="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>
        </div><div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
              <ul class="current">
<li class="toctree-l1"><a class="reference internal" href="introduction.html">Introduction</a></li>
<li class="toctree-l1"><a class="reference internal" href="installation.html">Installation</a></li>
<li class="toctree-l1"><a class="reference internal" href="key_concepts.html">Key Concepts</a></li>
<li class="toctree-l1"><a class="reference internal" href="key_concepts_builder.html">Key Concepts (builder mode)</a></li>
<li class="toctree-l1"><a class="reference internal" href="key_concepts_algebra.html">Key Concepts (algebra mode)</a></li>
<li class="toctree-l1"><a class="reference internal" href="moving_objects.html">Moving Objects</a></li>
<li class="toctree-l1"><a class="reference internal" href="OpenSCAD.html">Transitioning from OpenSCAD</a></li>
<li class="toctree-l1"><a class="reference internal" href="introductory_examples.html">Introductory Examples</a></li>
<li class="toctree-l1 current"><a class="reference internal" href="tutorials.html">Tutorials</a><ul class="current">
<li class="toctree-l2"><a class="reference internal" href="tutorial_design.html">Designing a Part in build123d</a></li>
<li class="toctree-l2"><a class="reference internal" href="tutorial_selectors.html">Selector Tutorial</a></li>
<li class="toctree-l2 current"><a class="current reference internal" href="#">Lego Tutorial</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#step-1-setup">Step 1: Setup</a></li>
<li class="toctree-l3"><a class="reference internal" href="#step-2-part-builder">Step 2: Part Builder</a></li>
<li class="toctree-l3"><a class="reference internal" href="#step-3-sketch-builder">Step 3: Sketch Builder</a></li>
<li class="toctree-l3"><a class="reference internal" href="#step-4-perimeter-rectangle">Step 4: Perimeter Rectangle</a></li>
<li class="toctree-l3"><a class="reference internal" href="#step-5-offset-to-create-walls">Step 5: Offset to Create Walls</a></li>
<li class="toctree-l3"><a class="reference internal" href="#step-6-create-internal-grid">Step 6: Create Internal Grid</a></li>
<li class="toctree-l3"><a class="reference internal" href="#step-7-create-ridges">Step 7: Create Ridges</a></li>
<li class="toctree-l3"><a class="reference internal" href="#step-8-hollow-circles">Step 8: Hollow Circles</a></li>
<li class="toctree-l3"><a class="reference internal" href="#step-9-extruding-sketch-into-walls">Step 9: Extruding Sketch into Walls</a></li>
<li class="toctree-l3"><a class="reference internal" href="#step-10-adding-a-top">Step 10: Adding a Top</a></li>
<li class="toctree-l3"><a class="reference internal" href="#step-11-adding-pips">Step 11: Adding Pips</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="tutorial_joints.html">Joint Tutorial</a></li>
<li class="toctree-l2"><a class="reference internal" href="examples_1.html">The build123d Examples</a></li>
<li class="toctree-l2"><a class="reference internal" href="tttt.html">Too Tall Toby (TTT) Tutorials</a></li>
<li class="toctree-l2"><a class="reference internal" href="tutorial_surface_modeling.html">Surface Modeling</a></li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="objects.html">Objects</a></li>
<li class="toctree-l1"><a class="reference internal" href="selectors_operators.html">Selectors and Operators</a></li>
<li class="toctree-l1"><a class="reference internal" href="operations.html">Operations</a></li>
<li class="toctree-l1"><a class="reference internal" href="builders.html">Builders</a></li>
<li class="toctree-l1"><a class="reference internal" href="joints.html">Joints</a></li>
<li class="toctree-l1"><a class="reference internal" href="assemblies.html">Assemblies</a></li>
<li class="toctree-l1"><a class="reference internal" href="tips.html">Tips, Best Practices and FAQ</a></li>
<li class="toctree-l1"><a class="reference internal" href="import_export.html">Import/Export</a></li>
<li class="toctree-l1"><a class="reference internal" href="advanced.html">Advanced Topics</a></li>
<li class="toctree-l1"><a class="reference internal" href="cheat_sheet.html">Cheat Sheet</a></li>
<li class="toctree-l1"><a class="reference internal" href="external.html">External Tools and Libraries</a></li>
<li class="toctree-l1"><a class="reference internal" href="builder_api_reference.html">Builder Common API Reference</a></li>
<li class="toctree-l1"><a class="reference internal" href="direct_api_reference.html">Direct API Reference</a></li>
</ul>

        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap"><nav class="wy-nav-top" aria-label="Mobile navigation menu" >
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="index.html">build123d</a>
      </nav>

      <div class="wy-nav-content">
        <div class="rst-content">
          <div role="navigation" aria-label="Page navigation">
  <ul class="wy-breadcrumbs">
      <li><a href="index.html" class="icon icon-home" aria-label="Home"></a></li>
          <li class="breadcrumb-item"><a href="tutorials.html">Tutorials</a></li>
      <li class="breadcrumb-item active">Lego Tutorial</li>
      <li class="wy-breadcrumbs-aside">
            <a href="_sources/tutorial_lego.rst.txt" rel="nofollow"> View page source</a>
      </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
             
  <section id="lego-tutorial">
<h1>Lego Tutorial<a class="headerlink" href="#lego-tutorial" title="Link to this heading"></a></h1>
<p>This tutorial provides a step by step guide to creating a script to build a parametric
Lego block as shown here:</p>
<img alt="_images/lego.svg" class="align-center" src="_images/lego.svg" />
<section id="step-1-setup">
<h2>Step 1: Setup<a class="headerlink" href="#step-1-setup" title="Link to this heading"></a></h2>
<p>Before getting to the CAD operations, this Lego script needs to import the build123d
environment. There are over 100 python classes in build123d so we’ll just import them
all with a <code class="docutils literal notranslate"><span class="pre">from</span> <span class="pre">build123d</span> <span class="pre">import</span> <span class="pre">*</span></code> but <a class="reference internal" href="tips.html#are-glob-imports-bad-practice"><span class="std std-ref">there are other options</span></a> that we won’t explore
here.</p>
<p>The dimensions of the Lego block follow. A key parameter is <code class="docutils literal notranslate"><span class="pre">pip_count</span></code>, the length
of the Lego blocks in pips. This parameter must be at least 2.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="kn">from</span><span class="w"> </span><span class="nn">build123d</span><span class="w"> </span><span class="kn">import</span> <span class="o">*</span>
<span class="kn">from</span><span class="w"> </span><span class="nn">ocp_vscode</span><span class="w"> </span><span class="kn">import</span> <span class="n">show_object</span>
<span class="n">pip_count</span> <span class="o">=</span> <span class="mi">6</span>

<span class="n">lego_unit_size</span> <span class="o">=</span> <span class="mi">8</span>
<span class="n">pip_height</span> <span class="o">=</span> <span class="mf">1.8</span>
<span class="n">pip_diameter</span> <span class="o">=</span> <span class="mf">4.8</span>
<span class="n">block_length</span> <span class="o">=</span> <span class="n">lego_unit_size</span> <span class="o">*</span> <span class="n">pip_count</span>
<span class="n">block_width</span> <span class="o">=</span> <span class="mi">16</span>
<span class="n">base_height</span> <span class="o">=</span> <span class="mf">9.6</span>
<span class="n">block_height</span> <span class="o">=</span> <span class="n">base_height</span> <span class="o">+</span> <span class="n">pip_height</span>
<span class="n">support_outer_diameter</span> <span class="o">=</span> <span class="mf">6.5</span>
<span class="n">support_inner_diameter</span> <span class="o">=</span> <span class="mf">4.8</span>
<span class="n">ridge_width</span> <span class="o">=</span> <span class="mf">0.6</span>
<span class="n">ridge_depth</span> <span class="o">=</span> <span class="mf">0.3</span>
<span class="n">wall_thickness</span> <span class="o">=</span> <span class="mf">1.2</span>
</pre></div>
</div>
</section>
<section id="step-2-part-builder">
<h2>Step 2: Part Builder<a class="headerlink" href="#step-2-part-builder" title="Link to this heading"></a></h2>
<p>The Lego block will be created by the <code class="docutils literal notranslate"><span class="pre">BuildPart</span></code> builder as it’s a discrete three
dimensional part; therefore, we’ll instantiate a <code class="docutils literal notranslate"><span class="pre">BuildPart</span></code> with the name <code class="docutils literal notranslate"><span class="pre">lego</span></code>.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">lego</span><span class="p">:</span>
</pre></div>
</div>
</section>
<section id="step-3-sketch-builder">
<h2>Step 3: Sketch Builder<a class="headerlink" href="#step-3-sketch-builder" title="Link to this heading"></a></h2>
<p>Lego blocks have quite a bit of internal structure. To create this structure we’ll
draw a two dimensional sketch that will later be extruded into a three dimensional
object.  As this sketch will be part of the lego part, we’ll create a sketch builder
in the context of the part builder as follows:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">lego</span><span class="p">:</span>
    <span class="c1"># Draw the bottom of the block</span>
<span class="hll">    <span class="k">with</span> <span class="n">BuildSketch</span><span class="p">()</span> <span class="k">as</span> <span class="n">plan</span><span class="p">:</span>
</span></pre></div>
</div>
<p>Note that builder instance names are optional - we’ll use <code class="docutils literal notranslate"><span class="pre">plan</span></code> to reference the sketch.
Also note that all sketch objects are filled or 2D faces not just perimeter lines.</p>
</section>
<section id="step-4-perimeter-rectangle">
<h2>Step 4: Perimeter Rectangle<a class="headerlink" href="#step-4-perimeter-rectangle" title="Link to this heading"></a></h2>
<p>The first object in the sketch is going to be a rectangle with the dimensions of the outside
of the Lego block. The following step is going to refer to this rectangle, so it will
be assigned the identifier <code class="docutils literal notranslate"><span class="pre">perimeter</span></code>.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">lego</span><span class="p">:</span>
    <span class="c1"># Draw the bottom of the block</span>
    <span class="k">with</span> <span class="n">BuildSketch</span><span class="p">()</span> <span class="k">as</span> <span class="n">plan</span><span class="p">:</span>
        <span class="c1"># Start with a Rectangle the size of the block</span>
<span class="hll">        <span class="n">perimeter</span> <span class="o">=</span> <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">block_width</span><span class="p">)</span>
</span></pre></div>
</div>
<p>Once the <code class="docutils literal notranslate"><span class="pre">Rectangle</span></code> object is created the sketch appears as follows:</p>
<img alt="_images/lego_step4.svg" class="align-center" src="_images/lego_step4.svg" />
</section>
<section id="step-5-offset-to-create-walls">
<h2>Step 5: Offset to Create Walls<a class="headerlink" href="#step-5-offset-to-create-walls" title="Link to this heading"></a></h2>
<p>To create the walls of the block the rectangle that we’ve created needs to be
hollowed out. This will be done with the <code class="docutils literal notranslate"><span class="pre">Offset</span></code> operation which is going to
create a new object from <code class="docutils literal notranslate"><span class="pre">perimeter</span></code>.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">lego</span><span class="p">:</span>
    <span class="c1"># Draw the bottom of the block</span>
    <span class="k">with</span> <span class="n">BuildSketch</span><span class="p">()</span> <span class="k">as</span> <span class="n">plan</span><span class="p">:</span>
        <span class="c1"># Start with a Rectangle the size of the block</span>
        <span class="n">perimeter</span> <span class="o">=</span> <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">block_width</span><span class="p">)</span>
        <span class="c1"># Subtract an offset to create the block walls</span>
<span class="hll">        <span class="n">offset</span><span class="p">(</span>
</span><span class="hll">            <span class="n">perimeter</span><span class="p">,</span>
</span><span class="hll">            <span class="o">-</span><span class="n">wall_thickness</span><span class="p">,</span>
</span><span class="hll">            <span class="n">kind</span><span class="o">=</span><span class="n">Kind</span><span class="o">.</span><span class="n">INTERSECTION</span><span class="p">,</span>
</span><span class="hll">            <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">,</span>
</span><span class="hll">        <span class="p">)</span>
</span></pre></div>
</div>
<p>The first parameter to <code class="docutils literal notranslate"><span class="pre">Offset</span></code> is the reference object. The <code class="docutils literal notranslate"><span class="pre">amount</span></code> is a
negative value to indicate that the offset should be internal. The <code class="docutils literal notranslate"><span class="pre">kind</span></code>
parameter controls the shape of the corners - <code class="docutils literal notranslate"><span class="pre">Kind.INTERSECTION</span></code> will create
square corners. Finally, the <code class="docutils literal notranslate"><span class="pre">mode</span></code> parameter controls how this object will
be placed in the sketch - in this case subtracted from the existing sketch.
The result is shown here:</p>
<img alt="_images/lego_step5.svg" class="align-center" src="_images/lego_step5.svg" />
<p>Now the sketch consists of a hollow rectangle.</p>
</section>
<section id="step-6-create-internal-grid">
<h2>Step 6: Create Internal Grid<a class="headerlink" href="#step-6-create-internal-grid" title="Link to this heading"></a></h2>
<p>The interior of the Lego block has small ridges on all four internal walls.
These ridges will be created as a grid of thin rectangles so the positions
of the centers of these rectangles need to be defined. A pair of
<code class="docutils literal notranslate"><span class="pre">GridLocations</span></code> location contexts will define these positions, one for
the horizontal bars and one for the vertical bars. As the <code class="docutils literal notranslate"><span class="pre">Rectangle</span></code>
objects are in the scope of a location context (<code class="docutils literal notranslate"><span class="pre">GridLocations</span></code> in this case)
that defined multiple points, multiple rectangles are created.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">lego</span><span class="p">:</span>
    <span class="c1"># Draw the bottom of the block</span>
    <span class="k">with</span> <span class="n">BuildSketch</span><span class="p">()</span> <span class="k">as</span> <span class="n">plan</span><span class="p">:</span>
        <span class="c1"># Start with a Rectangle the size of the block</span>
        <span class="n">perimeter</span> <span class="o">=</span> <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">block_width</span><span class="p">)</span>
        <span class="c1"># Subtract an offset to create the block walls</span>
        <span class="n">offset</span><span class="p">(</span>
            <span class="n">perimeter</span><span class="p">,</span>
            <span class="o">-</span><span class="n">wall_thickness</span><span class="p">,</span>
            <span class="n">kind</span><span class="o">=</span><span class="n">Kind</span><span class="o">.</span><span class="n">INTERSECTION</span><span class="p">,</span>
            <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">,</span>
        <span class="p">)</span>
<span class="hll">        <span class="c1"># Add a grid of lengthwise and widthwise bars</span>
</span><span class="hll">        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span><span class="n">x_spacing</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">y_spacing</span><span class="o">=</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="n">x_count</span><span class="o">=</span><span class="mi">1</span><span class="p">,</span> <span class="n">y_count</span><span class="o">=</span><span class="mi">2</span><span class="p">):</span>
</span><span class="hll">            <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">ridge_width</span><span class="p">)</span>
</span><span class="hll">        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">pip_count</span><span class="p">,</span> <span class="mi">1</span><span class="p">):</span>
</span><span class="hll">            <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">ridge_width</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">block_width</span><span class="p">)</span>
</span></pre></div>
</div>
<p>Here we can see that the first <code class="docutils literal notranslate"><span class="pre">GridLocations</span></code> creates two positions which causes
two horizontal rectangles to be created.  The second <code class="docutils literal notranslate"><span class="pre">GridLocations</span></code> works in the same way
but creates <code class="docutils literal notranslate"><span class="pre">pip_count</span></code> positions and therefore <code class="docutils literal notranslate"><span class="pre">pip_count</span></code> rectangles. Note that keyword
parameter are optional in this case.</p>
<p>The result looks like this:</p>
<img alt="_images/lego_step6.svg" class="align-center" src="_images/lego_step6.svg" />
</section>
<section id="step-7-create-ridges">
<h2>Step 7: Create Ridges<a class="headerlink" href="#step-7-create-ridges" title="Link to this heading"></a></h2>
<p>To convert the internal grid to ridges, the center needs to be removed. This will be done
with another <code class="docutils literal notranslate"><span class="pre">Rectangle</span></code>.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">lego</span><span class="p">:</span>
    <span class="c1"># Draw the bottom of the block</span>
    <span class="k">with</span> <span class="n">BuildSketch</span><span class="p">()</span> <span class="k">as</span> <span class="n">plan</span><span class="p">:</span>
        <span class="c1"># Start with a Rectangle the size of the block</span>
        <span class="n">perimeter</span> <span class="o">=</span> <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">block_width</span><span class="p">)</span>
        <span class="c1"># Subtract an offset to create the block walls</span>
        <span class="n">offset</span><span class="p">(</span>
            <span class="n">perimeter</span><span class="p">,</span>
            <span class="o">-</span><span class="n">wall_thickness</span><span class="p">,</span>
            <span class="n">kind</span><span class="o">=</span><span class="n">Kind</span><span class="o">.</span><span class="n">INTERSECTION</span><span class="p">,</span>
            <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">,</span>
        <span class="p">)</span>
        <span class="c1"># Add a grid of lengthwise and widthwise bars</span>
        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span><span class="n">x_spacing</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">y_spacing</span><span class="o">=</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="n">x_count</span><span class="o">=</span><span class="mi">1</span><span class="p">,</span> <span class="n">y_count</span><span class="o">=</span><span class="mi">2</span><span class="p">):</span>
            <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">ridge_width</span><span class="p">)</span>
        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">pip_count</span><span class="p">,</span> <span class="mi">1</span><span class="p">):</span>
            <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">ridge_width</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">block_width</span><span class="p">)</span>
<span class="hll">        <span class="c1"># Substract a rectangle leaving ribs on the block walls</span>
</span><span class="hll">        <span class="n">Rectangle</span><span class="p">(</span>
</span><span class="hll">            <span class="n">block_length</span> <span class="o">-</span> <span class="mi">2</span> <span class="o">*</span> <span class="p">(</span><span class="n">wall_thickness</span> <span class="o">+</span> <span class="n">ridge_depth</span><span class="p">),</span>
</span><span class="hll">            <span class="n">block_width</span> <span class="o">-</span> <span class="mi">2</span> <span class="o">*</span> <span class="p">(</span><span class="n">wall_thickness</span> <span class="o">+</span> <span class="n">ridge_depth</span><span class="p">),</span>
</span><span class="hll">            <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">,</span>
</span><span class="hll">        <span class="p">)</span>
</span></pre></div>
</div>
<p>The <code class="docutils literal notranslate"><span class="pre">Rectangle</span></code> is subtracted from the sketch to leave the ridges as follows:</p>
<img alt="_images/lego_step7.svg" class="align-center" src="_images/lego_step7.svg" />
</section>
<section id="step-8-hollow-circles">
<h2>Step 8: Hollow Circles<a class="headerlink" href="#step-8-hollow-circles" title="Link to this heading"></a></h2>
<p>Lego blocks use a set of internal hollow cylinders that the pips push against
to hold two blocks together. These will be created with <code class="docutils literal notranslate"><span class="pre">Circle</span></code>.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">lego</span><span class="p">:</span>
    <span class="c1"># Draw the bottom of the block</span>
    <span class="k">with</span> <span class="n">BuildSketch</span><span class="p">()</span> <span class="k">as</span> <span class="n">plan</span><span class="p">:</span>
        <span class="c1"># Start with a Rectangle the size of the block</span>
        <span class="n">perimeter</span> <span class="o">=</span> <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">block_width</span><span class="p">)</span>
        <span class="c1"># Subtract an offset to create the block walls</span>
        <span class="n">offset</span><span class="p">(</span>
            <span class="n">perimeter</span><span class="p">,</span>
            <span class="o">-</span><span class="n">wall_thickness</span><span class="p">,</span>
            <span class="n">kind</span><span class="o">=</span><span class="n">Kind</span><span class="o">.</span><span class="n">INTERSECTION</span><span class="p">,</span>
            <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">,</span>
        <span class="p">)</span>
        <span class="c1"># Add a grid of lengthwise and widthwise bars</span>
        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span><span class="n">x_spacing</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">y_spacing</span><span class="o">=</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="n">x_count</span><span class="o">=</span><span class="mi">1</span><span class="p">,</span> <span class="n">y_count</span><span class="o">=</span><span class="mi">2</span><span class="p">):</span>
            <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">ridge_width</span><span class="p">)</span>
        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">pip_count</span><span class="p">,</span> <span class="mi">1</span><span class="p">):</span>
            <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">ridge_width</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">block_width</span><span class="p">)</span>
        <span class="c1"># Substract a rectangle leaving ribs on the block walls</span>
        <span class="n">Rectangle</span><span class="p">(</span>
            <span class="n">block_length</span> <span class="o">-</span> <span class="mi">2</span> <span class="o">*</span> <span class="p">(</span><span class="n">wall_thickness</span> <span class="o">+</span> <span class="n">ridge_depth</span><span class="p">),</span>
            <span class="n">block_width</span> <span class="o">-</span> <span class="mi">2</span> <span class="o">*</span> <span class="p">(</span><span class="n">wall_thickness</span> <span class="o">+</span> <span class="n">ridge_depth</span><span class="p">),</span>
            <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">,</span>
        <span class="p">)</span>
<span class="hll">        <span class="c1"># Add a row of hollow circles to the center</span>
</span><span class="hll">        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span>
</span><span class="hll">            <span class="n">x_spacing</span><span class="o">=</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="n">y_spacing</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">x_count</span><span class="o">=</span><span class="n">pip_count</span> <span class="o">-</span> <span class="mi">1</span><span class="p">,</span> <span class="n">y_count</span><span class="o">=</span><span class="mi">1</span>
</span><span class="hll">        <span class="p">):</span>
</span><span class="hll">            <span class="n">Circle</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="n">support_outer_diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)</span>
</span><span class="hll">            <span class="n">Circle</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="n">support_inner_diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">)</span>
</span></pre></div>
</div>
<p>Here another <code class="docutils literal notranslate"><span class="pre">GridLocations</span></code> is used to position the centers of the circles.  Note
that since both <code class="docutils literal notranslate"><span class="pre">Circle</span></code> objects are in the scope of the location context, both
Circles will be positioned at these locations.</p>
<p>Once the Circles are added, the sketch is complete and looks as follows:</p>
<img alt="_images/lego_step8.svg" class="align-center" src="_images/lego_step8.svg" />
</section>
<section id="step-9-extruding-sketch-into-walls">
<h2>Step 9: Extruding Sketch into Walls<a class="headerlink" href="#step-9-extruding-sketch-into-walls" title="Link to this heading"></a></h2>
<p>Now that the sketch is complete it needs to be extruded into the three dimensional
wall object.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">lego</span><span class="p">:</span>
    <span class="c1"># Draw the bottom of the block</span>
    <span class="k">with</span> <span class="n">BuildSketch</span><span class="p">()</span> <span class="k">as</span> <span class="n">plan</span><span class="p">:</span>
        <span class="c1"># Start with a Rectangle the size of the block</span>
        <span class="n">perimeter</span> <span class="o">=</span> <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">block_width</span><span class="p">)</span>
        <span class="c1"># Subtract an offset to create the block walls</span>
        <span class="n">offset</span><span class="p">(</span>
            <span class="n">perimeter</span><span class="p">,</span>
            <span class="o">-</span><span class="n">wall_thickness</span><span class="p">,</span>
            <span class="n">kind</span><span class="o">=</span><span class="n">Kind</span><span class="o">.</span><span class="n">INTERSECTION</span><span class="p">,</span>
            <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">,</span>
        <span class="p">)</span>
        <span class="c1"># Add a grid of lengthwise and widthwise bars</span>
        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span><span class="n">x_spacing</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">y_spacing</span><span class="o">=</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="n">x_count</span><span class="o">=</span><span class="mi">1</span><span class="p">,</span> <span class="n">y_count</span><span class="o">=</span><span class="mi">2</span><span class="p">):</span>
            <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">ridge_width</span><span class="p">)</span>
        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">pip_count</span><span class="p">,</span> <span class="mi">1</span><span class="p">):</span>
            <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">ridge_width</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">block_width</span><span class="p">)</span>
        <span class="c1"># Substract a rectangle leaving ribs on the block walls</span>
        <span class="n">Rectangle</span><span class="p">(</span>
            <span class="n">block_length</span> <span class="o">-</span> <span class="mi">2</span> <span class="o">*</span> <span class="p">(</span><span class="n">wall_thickness</span> <span class="o">+</span> <span class="n">ridge_depth</span><span class="p">),</span>
            <span class="n">block_width</span> <span class="o">-</span> <span class="mi">2</span> <span class="o">*</span> <span class="p">(</span><span class="n">wall_thickness</span> <span class="o">+</span> <span class="n">ridge_depth</span><span class="p">),</span>
            <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">,</span>
        <span class="p">)</span>
        <span class="c1"># Add a row of hollow circles to the center</span>
        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span>
            <span class="n">x_spacing</span><span class="o">=</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="n">y_spacing</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">x_count</span><span class="o">=</span><span class="n">pip_count</span> <span class="o">-</span> <span class="mi">1</span><span class="p">,</span> <span class="n">y_count</span><span class="o">=</span><span class="mi">1</span>
        <span class="p">):</span>
            <span class="n">Circle</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="n">support_outer_diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)</span>
            <span class="n">Circle</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="n">support_inner_diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">)</span>
<span class="hll">    <span class="c1"># Extrude this base sketch to the height of the walls</span>
</span><span class="hll">    <span class="n">extrude</span><span class="p">(</span><span class="n">amount</span><span class="o">=</span><span class="n">base_height</span> <span class="o">-</span> <span class="n">wall_thickness</span><span class="p">)</span>
</span></pre></div>
</div>
<p>Note how the <code class="docutils literal notranslate"><span class="pre">Extrude</span></code> operation is no longer in the <code class="docutils literal notranslate"><span class="pre">BuildSketch</span></code> scope and has returned
back into the <code class="docutils literal notranslate"><span class="pre">BuildPart</span></code> scope. This causes <code class="docutils literal notranslate"><span class="pre">BuildSketch</span></code> to exit and transfer the
sketch that we’ve created to <code class="docutils literal notranslate"><span class="pre">BuildPart</span></code> for further processing by <code class="docutils literal notranslate"><span class="pre">Extrude</span></code>.</p>
<p>The result is:</p>
<img alt="_images/lego_step9.svg" class="align-center" src="_images/lego_step9.svg" />
</section>
<section id="step-10-adding-a-top">
<h2>Step 10: Adding a Top<a class="headerlink" href="#step-10-adding-a-top" title="Link to this heading"></a></h2>
<p>Now that the walls are complete, the top of the block needs to be added. Although this
could be done with another sketch, we’ll add a box to the top of the walls.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">lego</span><span class="p">:</span>
    <span class="c1"># Draw the bottom of the block</span>
    <span class="k">with</span> <span class="n">BuildSketch</span><span class="p">()</span> <span class="k">as</span> <span class="n">plan</span><span class="p">:</span>
        <span class="c1"># Start with a Rectangle the size of the block</span>
        <span class="n">perimeter</span> <span class="o">=</span> <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">block_width</span><span class="p">)</span>
        <span class="c1"># Subtract an offset to create the block walls</span>
        <span class="n">offset</span><span class="p">(</span>
            <span class="n">perimeter</span><span class="p">,</span>
            <span class="o">-</span><span class="n">wall_thickness</span><span class="p">,</span>
            <span class="n">kind</span><span class="o">=</span><span class="n">Kind</span><span class="o">.</span><span class="n">INTERSECTION</span><span class="p">,</span>
            <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">,</span>
        <span class="p">)</span>
        <span class="c1"># Add a grid of lengthwise and widthwise bars</span>
        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span><span class="n">x_spacing</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">y_spacing</span><span class="o">=</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="n">x_count</span><span class="o">=</span><span class="mi">1</span><span class="p">,</span> <span class="n">y_count</span><span class="o">=</span><span class="mi">2</span><span class="p">):</span>
            <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">ridge_width</span><span class="p">)</span>
        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">pip_count</span><span class="p">,</span> <span class="mi">1</span><span class="p">):</span>
            <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">ridge_width</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">block_width</span><span class="p">)</span>
        <span class="c1"># Substract a rectangle leaving ribs on the block walls</span>
        <span class="n">Rectangle</span><span class="p">(</span>
            <span class="n">block_length</span> <span class="o">-</span> <span class="mi">2</span> <span class="o">*</span> <span class="p">(</span><span class="n">wall_thickness</span> <span class="o">+</span> <span class="n">ridge_depth</span><span class="p">),</span>
            <span class="n">block_width</span> <span class="o">-</span> <span class="mi">2</span> <span class="o">*</span> <span class="p">(</span><span class="n">wall_thickness</span> <span class="o">+</span> <span class="n">ridge_depth</span><span class="p">),</span>
            <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">,</span>
        <span class="p">)</span>
        <span class="c1"># Add a row of hollow circles to the center</span>
        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span>
            <span class="n">x_spacing</span><span class="o">=</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="n">y_spacing</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">x_count</span><span class="o">=</span><span class="n">pip_count</span> <span class="o">-</span> <span class="mi">1</span><span class="p">,</span> <span class="n">y_count</span><span class="o">=</span><span class="mi">1</span>
        <span class="p">):</span>
            <span class="n">Circle</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="n">support_outer_diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)</span>
            <span class="n">Circle</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="n">support_inner_diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">)</span>
    <span class="c1"># Extrude this base sketch to the height of the walls</span>
    <span class="n">extrude</span><span class="p">(</span><span class="n">amount</span><span class="o">=</span><span class="n">base_height</span> <span class="o">-</span> <span class="n">wall_thickness</span><span class="p">)</span>
<span class="hll">    <span class="c1"># Create a box on the top of the walls</span>
</span><span class="hll">    <span class="k">with</span> <span class="n">Locations</span><span class="p">((</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">lego</span><span class="o">.</span><span class="n">vertices</span><span class="p">()</span><span class="o">.</span><span class="n">sort_by</span><span class="p">(</span><span class="n">Axis</span><span class="o">.</span><span class="n">Z</span><span class="p">)[</span><span class="o">-</span><span class="mi">1</span><span class="p">]</span><span class="o">.</span><span class="n">Z</span><span class="p">)):</span>
</span><span class="hll">        <span class="c1"># Create the top of the block</span>
</span><span class="hll">        <span class="n">Box</span><span class="p">(</span>
</span><span class="hll">            <span class="n">length</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span>
</span><span class="hll">            <span class="n">width</span><span class="o">=</span><span class="n">block_width</span><span class="p">,</span>
</span><span class="hll">            <span class="n">height</span><span class="o">=</span><span class="n">wall_thickness</span><span class="p">,</span>
</span><span class="hll">            <span class="n">align</span><span class="o">=</span><span class="p">(</span><span class="n">Align</span><span class="o">.</span><span class="n">CENTER</span><span class="p">,</span> <span class="n">Align</span><span class="o">.</span><span class="n">CENTER</span><span class="p">,</span> <span class="n">Align</span><span class="o">.</span><span class="n">MIN</span><span class="p">),</span>
</span><span class="hll">        <span class="p">)</span>
</span></pre></div>
</div>
<p>To position the top, we’ll describe the top center of the lego walls with a <code class="docutils literal notranslate"><span class="pre">Locations</span></code> context.
To determine the height we’ll extract that from the
<code class="docutils literal notranslate"><span class="pre">lego.part</span></code> by using the <code class="docutils literal notranslate"><span class="pre">vertices()</span></code> method which returns a list of the positions
of all of the vertices of the Lego block so far. Since we’re interested in the top,
we’ll sort by the vertical (Z) axis and take the top of the list <code class="docutils literal notranslate"><span class="pre">sort_by(Axis.Z)[-1]</span></code>. Finally,
the <code class="docutils literal notranslate"><span class="pre">Z</span></code> property of this vertex will return just the height of the top. Note that
the <code class="docutils literal notranslate"><span class="pre">X</span></code> and <code class="docutils literal notranslate"><span class="pre">Y</span></code> values are not used from the selected vertex as there are no
vertices in the center of the block.</p>
<p>Within the scope of this <code class="docutils literal notranslate"><span class="pre">Locations</span></code> context, a <code class="docutils literal notranslate"><span class="pre">Box</span></code> is created, centered at
the intersection of the x and y axis but not in the z thus aligning with the top of the walls.</p>
<p>The base is closed now as shown here:</p>
<img alt="_images/lego_step10.svg" class="align-center" src="_images/lego_step10.svg" />
</section>
<section id="step-11-adding-pips">
<h2>Step 11: Adding Pips<a class="headerlink" href="#step-11-adding-pips" title="Link to this heading"></a></h2>
<p>The final step is to add the pips to the top of the Lego block. To do this we’ll create
a new workplane on top of the block where we can position the pips.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">lego</span><span class="p">:</span>
    <span class="c1"># Draw the bottom of the block</span>
    <span class="k">with</span> <span class="n">BuildSketch</span><span class="p">()</span> <span class="k">as</span> <span class="n">plan</span><span class="p">:</span>
        <span class="c1"># Start with a Rectangle the size of the block</span>
        <span class="n">perimeter</span> <span class="o">=</span> <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">block_width</span><span class="p">)</span>
        <span class="c1"># Subtract an offset to create the block walls</span>
        <span class="n">offset</span><span class="p">(</span>
            <span class="n">perimeter</span><span class="p">,</span>
            <span class="o">-</span><span class="n">wall_thickness</span><span class="p">,</span>
            <span class="n">kind</span><span class="o">=</span><span class="n">Kind</span><span class="o">.</span><span class="n">INTERSECTION</span><span class="p">,</span>
            <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">,</span>
        <span class="p">)</span>
        <span class="c1"># Add a grid of lengthwise and widthwise bars</span>
        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span><span class="n">x_spacing</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">y_spacing</span><span class="o">=</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="n">x_count</span><span class="o">=</span><span class="mi">1</span><span class="p">,</span> <span class="n">y_count</span><span class="o">=</span><span class="mi">2</span><span class="p">):</span>
            <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">ridge_width</span><span class="p">)</span>
        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">pip_count</span><span class="p">,</span> <span class="mi">1</span><span class="p">):</span>
            <span class="n">Rectangle</span><span class="p">(</span><span class="n">width</span><span class="o">=</span><span class="n">ridge_width</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="n">block_width</span><span class="p">)</span>
        <span class="c1"># Substract a rectangle leaving ribs on the block walls</span>
        <span class="n">Rectangle</span><span class="p">(</span>
            <span class="n">block_length</span> <span class="o">-</span> <span class="mi">2</span> <span class="o">*</span> <span class="p">(</span><span class="n">wall_thickness</span> <span class="o">+</span> <span class="n">ridge_depth</span><span class="p">),</span>
            <span class="n">block_width</span> <span class="o">-</span> <span class="mi">2</span> <span class="o">*</span> <span class="p">(</span><span class="n">wall_thickness</span> <span class="o">+</span> <span class="n">ridge_depth</span><span class="p">),</span>
            <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">,</span>
        <span class="p">)</span>
        <span class="c1"># Add a row of hollow circles to the center</span>
        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span>
            <span class="n">x_spacing</span><span class="o">=</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="n">y_spacing</span><span class="o">=</span><span class="mi">0</span><span class="p">,</span> <span class="n">x_count</span><span class="o">=</span><span class="n">pip_count</span> <span class="o">-</span> <span class="mi">1</span><span class="p">,</span> <span class="n">y_count</span><span class="o">=</span><span class="mi">1</span>
        <span class="p">):</span>
            <span class="n">Circle</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="n">support_outer_diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">)</span>
            <span class="n">Circle</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="n">support_inner_diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">)</span>
    <span class="c1"># Extrude this base sketch to the height of the walls</span>
    <span class="n">extrude</span><span class="p">(</span><span class="n">amount</span><span class="o">=</span><span class="n">base_height</span> <span class="o">-</span> <span class="n">wall_thickness</span><span class="p">)</span>
    <span class="c1"># Create a box on the top of the walls</span>
    <span class="k">with</span> <span class="n">Locations</span><span class="p">((</span><span class="mi">0</span><span class="p">,</span> <span class="mi">0</span><span class="p">,</span> <span class="n">lego</span><span class="o">.</span><span class="n">vertices</span><span class="p">()</span><span class="o">.</span><span class="n">sort_by</span><span class="p">(</span><span class="n">Axis</span><span class="o">.</span><span class="n">Z</span><span class="p">)[</span><span class="o">-</span><span class="mi">1</span><span class="p">]</span><span class="o">.</span><span class="n">Z</span><span class="p">)):</span>
        <span class="c1"># Create the top of the block</span>
        <span class="n">Box</span><span class="p">(</span>
            <span class="n">length</span><span class="o">=</span><span class="n">block_length</span><span class="p">,</span>
            <span class="n">width</span><span class="o">=</span><span class="n">block_width</span><span class="p">,</span>
            <span class="n">height</span><span class="o">=</span><span class="n">wall_thickness</span><span class="p">,</span>
            <span class="n">align</span><span class="o">=</span><span class="p">(</span><span class="n">Align</span><span class="o">.</span><span class="n">CENTER</span><span class="p">,</span> <span class="n">Align</span><span class="o">.</span><span class="n">CENTER</span><span class="p">,</span> <span class="n">Align</span><span class="o">.</span><span class="n">MIN</span><span class="p">),</span>
        <span class="p">)</span>
<span class="hll">    <span class="c1"># Create a workplane on the top of the block</span>
</span><span class="hll">    <span class="k">with</span> <span class="n">BuildPart</span><span class="p">(</span><span class="n">lego</span><span class="o">.</span><span class="n">faces</span><span class="p">()</span><span class="o">.</span><span class="n">sort_by</span><span class="p">(</span><span class="n">Axis</span><span class="o">.</span><span class="n">Z</span><span class="p">)[</span><span class="o">-</span><span class="mi">1</span><span class="p">]):</span>
</span><span class="hll">        <span class="c1"># Create a grid of pips</span>
</span><span class="hll">        <span class="k">with</span> <span class="n">GridLocations</span><span class="p">(</span><span class="n">lego_unit_size</span><span class="p">,</span> <span class="n">lego_unit_size</span><span class="p">,</span> <span class="n">pip_count</span><span class="p">,</span> <span class="mi">2</span><span class="p">):</span>
</span><span class="hll">            <span class="n">Cylinder</span><span class="p">(</span>
</span><span class="hll">                <span class="n">radius</span><span class="o">=</span><span class="n">pip_diameter</span> <span class="o">/</span> <span class="mi">2</span><span class="p">,</span>
</span><span class="hll">                <span class="n">height</span><span class="o">=</span><span class="n">pip_height</span><span class="p">,</span>
</span><span class="hll">                <span class="n">align</span><span class="o">=</span><span class="p">(</span><span class="n">Align</span><span class="o">.</span><span class="n">CENTER</span><span class="p">,</span> <span class="n">Align</span><span class="o">.</span><span class="n">CENTER</span><span class="p">,</span> <span class="n">Align</span><span class="o">.</span><span class="n">MIN</span><span class="p">),</span>
</span><span class="hll">            <span class="p">)</span>
</span></pre></div>
</div>
<p>In this case, the workplane is created from the top Face of the Lego block by using the
<code class="docutils literal notranslate"><span class="pre">faces</span></code> method and then sorted vertically and taking the top one <code class="docutils literal notranslate"><span class="pre">sort_by(Axis.Z)[-1]</span></code>.</p>
<p>On the new workplane, a grid of locations is created and a number of <code class="docutils literal notranslate"><span class="pre">Cylinder</span></code>’s are positioned
at each location.</p>
<img alt="_images/lego.svg" class="align-center" src="_images/lego.svg" />
<p>This completes the Lego block. To access the finished product, refer to the builder’s internal
object as shown here:</p>
<table class="docutils align-default">
<thead>
<tr class="row-odd"><th class="head"><p>Builder</p></th>
<th class="head"><p>Object</p></th>
</tr>
</thead>
<tbody>
<tr class="row-even"><td><p>BuildLine</p></td>
<td><p>line</p></td>
</tr>
<tr class="row-odd"><td><p>BuildSketch</p></td>
<td><p>sketch</p></td>
</tr>
<tr class="row-even"><td><p>BuildPart</p></td>
<td><p>part</p></td>
</tr>
</tbody>
</table>
<p>so in this case the Lego block is <code class="docutils literal notranslate"><span class="pre">lego.part</span></code>. To display the part use <code class="docutils literal notranslate"><span class="pre">show_object(lego.part)</span></code>
or <code class="docutils literal notranslate"><span class="pre">show(lego.part)</span></code> depending on the viewer. The part could also be exported to a STL or STEP
file by referencing <code class="docutils literal notranslate"><span class="pre">lego.part</span></code>.</p>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Viewers that don’t directly support build123d my require a raw OpenCascade object. In this
case, append <code class="docutils literal notranslate"><span class="pre">.wrapped</span></code> to the object (e.g.) <code class="docutils literal notranslate"><span class="pre">show_object(lego.part.wrapped)</span></code>.</p>
</div>
</section>
</section>


           </div>
          </div>
          <footer><div class="rst-footer-buttons" role="navigation" aria-label="Footer">
        <a href="tutorial_selectors.html" class="btn btn-neutral float-left" title="Selector Tutorial" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left" aria-hidden="true"></span> Previous</a>
        <a href="tutorial_joints.html" class="btn btn-neutral float-right" title="Joint Tutorial" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right" aria-hidden="true"></span></a>
    </div>

  <hr/>

  <div role="contentinfo">
    <p>&#169; Copyright 2022, Gumyr.</p>
  </div>

  Built with <a href="https://www.sphinx-doc.org/">Sphinx</a> using a
    <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a>
    provided by <a href="https://readthedocs.org">Read the Docs</a>.
   

</footer>
        </div>
      </div>
    </section>
  </div>
  <script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>