

<!DOCTYPE html>
<html class="writer-html5" lang="en" data-content_root="./">
<head>
  <meta charset="utf-8" /><meta name="viewport" content="width=device-width, initial-scale=1" />

  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>Selector Tutorial &mdash; build123d 0.9.2.dev40+gb1f0eed documentation</title>
      <link rel="stylesheet" type="text/css" href="_static/pygments.css?v=b86133f3" />
      <link rel="stylesheet" type="text/css" href="_static/css/theme.css?v=e59714d7" />
      <link rel="stylesheet" type="text/css" href="_static/graphviz.css?v=4ae1632d" />
      <link rel="stylesheet" type="text/css" href="_static/copybutton.css?v=76b2166b" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster.custom.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster.bundle.min.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster-sideTip-shadow.min.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster-sideTip-punk.min.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster-sideTip-noir.min.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster-sideTip-light.min.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/tooltipster-sideTip-borderless.min.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/micromodal.css" />
      <link rel="stylesheet" type="text/css" href="_static/css/sphinx_rtd_theme.css?v=3234e928" />
      <link rel="stylesheet" type="text/css" href="_static/sphinx-design.min.css?v=95c83b7e" />

  
      <script src="_static/jquery.js?v=5d32c60e"></script>
      <script src="_static/_sphinx_javascript_frameworks_compat.js?v=2cd50e6c"></script>
      <script src="_static/documentation_options.js?v=c97902b4"></script>
      <script src="_static/doctools.js?v=9bcbadda"></script>
      <script src="_static/sphinx_highlight.js?v=dc90522c"></script>
      <script src="_static/clipboard.min.js?v=a7894cd8"></script>
      <script src="_static/copybutton.js?v=f281be69"></script>
      <script src="_static/js/hoverxref.js"></script>
      <script src="_static/js/tooltipster.bundle.min.js"></script>
      <script src="_static/js/micromodal.min.js"></script>
      <script src="_static/design-tabs.js?v=f930bc37"></script>
      <script async="async" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js"></script>
    <script src="_static/js/theme.js"></script>
    <link rel="index" title="Index" href="genindex.html" />
    <link rel="search" title="Search" href="search.html" />
    <link rel="next" title="Lego Tutorial" href="tutorial_lego.html" />
    <link rel="prev" title="Designing a Part in build123d" href="tutorial_design.html" /> 
</head>

<body class="wy-body-for-nav"> 
  <div class="wy-grid-for-nav">
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >

          
          
          <a href="index.html" class="icon icon-home">
            build123d
              <img src="_static/logo.svg" class="logo" alt="Logo"/>
          </a>
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" aria-label="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>
        </div><div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="Navigation menu">
              <ul class="current">
<li class="toctree-l1"><a class="reference internal" href="introduction.html">Introduction</a></li>
<li class="toctree-l1"><a class="reference internal" href="installation.html">Installation</a></li>
<li class="toctree-l1"><a class="reference internal" href="key_concepts.html">Key Concepts</a></li>
<li class="toctree-l1"><a class="reference internal" href="key_concepts_builder.html">Key Concepts (builder mode)</a></li>
<li class="toctree-l1"><a class="reference internal" href="key_concepts_algebra.html">Key Concepts (algebra mode)</a></li>
<li class="toctree-l1"><a class="reference internal" href="moving_objects.html">Moving Objects</a></li>
<li class="toctree-l1"><a class="reference internal" href="OpenSCAD.html">Transitioning from OpenSCAD</a></li>
<li class="toctree-l1"><a class="reference internal" href="introductory_examples.html">Introductory Examples</a></li>
<li class="toctree-l1 current"><a class="reference internal" href="tutorials.html">Tutorials</a><ul class="current">
<li class="toctree-l2"><a class="reference internal" href="tutorial_design.html">Designing a Part in build123d</a></li>
<li class="toctree-l2 current"><a class="current reference internal" href="#">Selector Tutorial</a><ul>
<li class="toctree-l3"><a class="reference internal" href="#step-1-setup">Step 1: Setup</a></li>
<li class="toctree-l3"><a class="reference internal" href="#step-2-create-base-with-buildpart">Step 2: Create Base with BuildPart</a></li>
<li class="toctree-l3"><a class="reference internal" href="#step-3-place-sketch-on-top-of-base">Step 3: Place Sketch on top of base</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#step-3a-extract-faces-from-a-part">Step 3a: Extract Faces from a part</a></li>
<li class="toctree-l4"><a class="reference internal" href="#step-3b-get-top-face">Step 3b: Get top Face</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#step-4-create-hole-shape">Step 4: Create hole shape</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#step-4a-draw-a-hexagon">Step 4a: Draw a hexagon</a></li>
<li class="toctree-l4"><a class="reference internal" href="#step-4b-create-a-hole-in-the-hexagon">Step 4b: Create a hole in the hexagon</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#step-5-create-the-hole">Step 5: Create the hole</a></li>
<li class="toctree-l3"><a class="reference internal" href="#step-6-fillet-the-top-perimeter-edge">Step 6: Fillet the top perimeter Edge</a><ul>
<li class="toctree-l4"><a class="reference internal" href="#step-6a-extract-all-the-edges">Step 6a: Extract all the Edges</a></li>
<li class="toctree-l4"><a class="reference internal" href="#step-6b-filter-the-edges-for-circles">Step 6b: Filter the Edges for circles</a></li>
<li class="toctree-l4"><a class="reference internal" href="#step-6c-sort-the-circles-by-radius">Step 6c: Sort the circles by radius</a></li>
<li class="toctree-l4"><a class="reference internal" href="#step-6d-slice-the-list-to-get-the-two-largest">Step 6d: Slice the list to get the two largest</a></li>
<li class="toctree-l4"><a class="reference internal" href="#step-6e-select-the-top-edge">Step 6e: Select the top Edge</a></li>
</ul>
</li>
<li class="toctree-l3"><a class="reference internal" href="#conclusion">Conclusion</a></li>
</ul>
</li>
<li class="toctree-l2"><a class="reference internal" href="tutorial_lego.html">Lego Tutorial</a></li>
<li class="toctree-l2"><a class="reference internal" href="tutorial_joints.html">Joint Tutorial</a></li>
<li class="toctree-l2"><a class="reference internal" href="examples_1.html">The build123d Examples</a></li>
<li class="toctree-l2"><a class="reference internal" href="tttt.html">Too Tall Toby (TTT) Tutorials</a></li>
<li class="toctree-l2"><a class="reference internal" href="tutorial_surface_modeling.html">Surface Modeling</a></li>
</ul>
</li>
<li class="toctree-l1"><a class="reference internal" href="objects.html">Objects</a></li>
<li class="toctree-l1"><a class="reference internal" href="selectors_operators.html">Selectors and Operators</a></li>
<li class="toctree-l1"><a class="reference internal" href="operations.html">Operations</a></li>
<li class="toctree-l1"><a class="reference internal" href="builders.html">Builders</a></li>
<li class="toctree-l1"><a class="reference internal" href="joints.html">Joints</a></li>
<li class="toctree-l1"><a class="reference internal" href="assemblies.html">Assemblies</a></li>
<li class="toctree-l1"><a class="reference internal" href="tips.html">Tips, Best Practices and FAQ</a></li>
<li class="toctree-l1"><a class="reference internal" href="import_export.html">Import/Export</a></li>
<li class="toctree-l1"><a class="reference internal" href="advanced.html">Advanced Topics</a></li>
<li class="toctree-l1"><a class="reference internal" href="cheat_sheet.html">Cheat Sheet</a></li>
<li class="toctree-l1"><a class="reference internal" href="external.html">External Tools and Libraries</a></li>
<li class="toctree-l1"><a class="reference internal" href="builder_api_reference.html">Builder Common API Reference</a></li>
<li class="toctree-l1"><a class="reference internal" href="direct_api_reference.html">Direct API Reference</a></li>
</ul>

        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap"><nav class="wy-nav-top" aria-label="Mobile navigation menu" >
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="index.html">build123d</a>
      </nav>

      <div class="wy-nav-content">
        <div class="rst-content">
          <div role="navigation" aria-label="Page navigation">
  <ul class="wy-breadcrumbs">
      <li><a href="index.html" class="icon icon-home" aria-label="Home"></a></li>
          <li class="breadcrumb-item"><a href="tutorials.html">Tutorials</a></li>
      <li class="breadcrumb-item active">Selector Tutorial</li>
      <li class="wy-breadcrumbs-aside">
            <a href="_sources/tutorial_selectors.rst.txt" rel="nofollow"> View page source</a>
      </li>
  </ul>
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
             
  <section id="selector-tutorial">
<h1>Selector Tutorial<a class="headerlink" href="#selector-tutorial" title="Link to this heading"></a></h1>
<p>This tutorial provides a step by step guide in using selectors as we create
this part:</p>
<img alt="_images/selector_after.svg" class="align-center" src="_images/selector_after.svg" />
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>One can see any object in the following tutorial by using the <code class="docutils literal notranslate"><span class="pre">ocp_vscode</span></code> (or
any other supported viewer) by using the <code class="docutils literal notranslate"><span class="pre">show(object_to_be_viewed)</span></code> command.
Alternatively, the <code class="docutils literal notranslate"><span class="pre">show_all()</span></code> command will display all objects that have been
assigned an identifier.</p>
</div>
<section id="step-1-setup">
<h2>Step 1: Setup<a class="headerlink" href="#step-1-setup" title="Link to this heading"></a></h2>
<p>Before getting to the CAD operations, this selector script needs to import the build123d
environment.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="kn">from</span><span class="w"> </span><span class="nn">build123d</span><span class="w"> </span><span class="kn">import</span> <span class="o">*</span>
<span class="kn">from</span><span class="w"> </span><span class="nn">ocp_vscode</span><span class="w"> </span><span class="kn">import</span> <span class="o">*</span>
</pre></div>
</div>
</section>
<section id="step-2-create-base-with-buildpart">
<h2>Step 2: Create Base with BuildPart<a class="headerlink" href="#step-2-create-base-with-buildpart" title="Link to this heading"></a></h2>
<p>To start off, the part will be based on a cylinder so we’ll use the <a class="hxr-hoverxref hxr-tooltip reference internal" href="objects.html#objects_part.Cylinder" title="objects_part.Cylinder"><code class="xref py py-class docutils literal notranslate"><span class="pre">Cylinder</span></code></a> object
of <a class="hxr-hoverxref hxr-tooltip reference internal" href="build_part.html#build_part.BuildPart" title="build_part.BuildPart"><code class="xref py py-class docutils literal notranslate"><span class="pre">BuildPart</span></code></a>:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="kn">from</span><span class="w"> </span><span class="nn">build123d</span><span class="w"> </span><span class="kn">import</span> <span class="o">*</span>
<span class="kn">from</span><span class="w"> </span><span class="nn">ocp_vscode</span><span class="w"> </span><span class="kn">import</span> <span class="o">*</span>

<span class="hll"><span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">example</span><span class="p">:</span>
</span><span class="hll">    <span class="n">Cylinder</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="mi">10</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="mi">3</span><span class="p">)</span>
</span></pre></div>
</div>
</section>
<section id="step-3-place-sketch-on-top-of-base">
<h2>Step 3: Place Sketch on top of base<a class="headerlink" href="#step-3-place-sketch-on-top-of-base" title="Link to this heading"></a></h2>
<p>The next set of features in this design will be created on the top of the cylinder
and be described by a planar sketch (<a class="hxr-hoverxref hxr-tooltip reference internal" href="build_sketch.html#build_sketch.BuildSketch" title="build_sketch.BuildSketch"><code class="xref py py-class docutils literal notranslate"><span class="pre">BuildSketch</span></code></a> is the tool for drawing on planar
surfaces) , so we’ll create a sketch centered on the top of the cylinder.  To locate
this sketch we’ll use the cylinder’s top Face as shown here:</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="kn">from</span><span class="w"> </span><span class="nn">build123d</span><span class="w"> </span><span class="kn">import</span> <span class="o">*</span>
<span class="kn">from</span><span class="w"> </span><span class="nn">ocp_vscode</span><span class="w"> </span><span class="kn">import</span> <span class="o">*</span>

<span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">example</span><span class="p">:</span>
    <span class="n">Cylinder</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="mi">10</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="mi">3</span><span class="p">)</span>
<span class="hll">    <span class="k">with</span> <span class="n">BuildSketch</span><span class="p">(</span><span class="n">example</span><span class="o">.</span><span class="n">faces</span><span class="p">()</span><span class="o">.</span><span class="n">sort_by</span><span class="p">(</span><span class="n">Axis</span><span class="o">.</span><span class="n">Z</span><span class="p">)[</span><span class="o">-</span><span class="mi">1</span><span class="p">]):</span>
</span></pre></div>
</div>
<p>Here we’re using selectors to find that top Face - let’s break down
<code class="docutils literal notranslate"><span class="pre">example.faces().sort_by(Axis.Z)[-1]</span></code>:</p>
<section id="step-3a-extract-faces-from-a-part">
<h3>Step 3a: Extract Faces from a part<a class="headerlink" href="#step-3a-extract-faces-from-a-part" title="Link to this heading"></a></h3>
<p>The first sub-step is the extraction of all of the Faces from the part that we’re
building. The <a class="hxr-hoverxref hxr-tooltip reference internal" href="build_part.html#build_part.BuildPart" title="build_part.BuildPart"><code class="xref py py-class docutils literal notranslate"><span class="pre">BuildPart</span></code></a> instance was assigned the identifier <code class="docutils literal notranslate"><span class="pre">example</span></code> so
<code class="docutils literal notranslate"><span class="pre">example.faces()</span></code> will extract all of the Faces from that part into a custom
python <code class="docutils literal notranslate"><span class="pre">list</span></code> - a <a class="hxr-hoverxref hxr-tooltip reference internal" href="direct_api_reference.html#topology.ShapeList" title="topology.ShapeList"><code class="xref py py-class docutils literal notranslate"><span class="pre">ShapeList</span></code></a>.</p>
</section>
<section id="step-3b-get-top-face">
<h3>Step 3b: Get top Face<a class="headerlink" href="#step-3b-get-top-face" title="Link to this heading"></a></h3>
<p>The next sub-step is to sort the ShapeList of Faces by their position with
respect to the Z Axis. The <code class="docutils literal notranslate"><span class="pre">sort_by</span></code> method will sort the list by relative position
of the object’s center to the <code class="docutils literal notranslate"><span class="pre">Axis.Z</span></code> and <code class="docutils literal notranslate"><span class="pre">[-1]</span></code>
selects the last item on that list - or return the top Face of the <code class="docutils literal notranslate"><span class="pre">example</span></code> part.</p>
</section>
</section>
<section id="step-4-create-hole-shape">
<h2>Step 4: Create hole shape<a class="headerlink" href="#step-4-create-hole-shape" title="Link to this heading"></a></h2>
<p>The object has a hexagonal hole in the top with a central cylinder which we’ll describe
in the sketch.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="kn">from</span><span class="w"> </span><span class="nn">build123d</span><span class="w"> </span><span class="kn">import</span> <span class="o">*</span>
<span class="kn">from</span><span class="w"> </span><span class="nn">ocp_vscode</span><span class="w"> </span><span class="kn">import</span> <span class="o">*</span>

<span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">example</span><span class="p">:</span>
    <span class="n">Cylinder</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="mi">10</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="mi">3</span><span class="p">)</span>
    <span class="k">with</span> <span class="n">BuildSketch</span><span class="p">(</span><span class="n">example</span><span class="o">.</span><span class="n">faces</span><span class="p">()</span><span class="o">.</span><span class="n">sort_by</span><span class="p">(</span><span class="n">Axis</span><span class="o">.</span><span class="n">Z</span><span class="p">)[</span><span class="o">-</span><span class="mi">1</span><span class="p">]):</span>
<span class="hll">        <span class="n">RegularPolygon</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="mi">7</span><span class="p">,</span> <span class="n">side_count</span><span class="o">=</span><span class="mi">6</span><span class="p">)</span>
</span><span class="hll">        <span class="n">Circle</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="mi">4</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">)</span>
</span></pre></div>
</div>
<section id="step-4a-draw-a-hexagon">
<h3>Step 4a: Draw a hexagon<a class="headerlink" href="#step-4a-draw-a-hexagon" title="Link to this heading"></a></h3>
<p>We’ll create a hexagon with the use of <a class="hxr-hoverxref hxr-tooltip reference internal" href="objects.html#objects_sketch.RegularPolygon" title="objects_sketch.RegularPolygon"><code class="xref py py-class docutils literal notranslate"><span class="pre">RegularPolygon</span></code></a> object with six sides.</p>
</section>
<section id="step-4b-create-a-hole-in-the-hexagon">
<h3>Step 4b: Create a hole in the hexagon<a class="headerlink" href="#step-4b-create-a-hole-in-the-hexagon" title="Link to this heading"></a></h3>
<p>To create the hole we’ll subtract a <a class="hxr-hoverxref hxr-tooltip reference internal" href="objects.html#objects_sketch.Circle" title="objects_sketch.Circle"><code class="xref py py-class docutils literal notranslate"><span class="pre">Circle</span></code></a> from the sketch by using
<code class="docutils literal notranslate"><span class="pre">mode=Mode.SUBTRACT</span></code>. The sketch now described the hexagonal hole that we
want to make in the <a class="hxr-hoverxref hxr-tooltip reference internal" href="objects.html#objects_part.Cylinder" title="objects_part.Cylinder"><code class="xref py py-class docutils literal notranslate"><span class="pre">Cylinder</span></code></a>.</p>
</section>
</section>
<section id="step-5-create-the-hole">
<h2>Step 5: Create the hole<a class="headerlink" href="#step-5-create-the-hole" title="Link to this heading"></a></h2>
<p>To create the hole we’ll <a class="hxr-hoverxref hxr-tooltip reference internal" href="operations.html#operations_part.extrude" title="operations_part.extrude"><code class="xref py py-func docutils literal notranslate"><span class="pre">extrude()</span></code></a> the sketch we just created into
the <a class="hxr-hoverxref hxr-tooltip reference internal" href="objects.html#objects_part.Cylinder" title="objects_part.Cylinder"><code class="xref py py-class docutils literal notranslate"><span class="pre">Cylinder</span></code></a> and subtract it.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="kn">from</span><span class="w"> </span><span class="nn">build123d</span><span class="w"> </span><span class="kn">import</span> <span class="o">*</span>
<span class="kn">from</span><span class="w"> </span><span class="nn">ocp_vscode</span><span class="w"> </span><span class="kn">import</span> <span class="o">*</span>

<span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">example</span><span class="p">:</span>
    <span class="n">Cylinder</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="mi">10</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="mi">3</span><span class="p">)</span>
    <span class="k">with</span> <span class="n">BuildSketch</span><span class="p">(</span><span class="n">example</span><span class="o">.</span><span class="n">faces</span><span class="p">()</span><span class="o">.</span><span class="n">sort_by</span><span class="p">(</span><span class="n">Axis</span><span class="o">.</span><span class="n">Z</span><span class="p">)[</span><span class="o">-</span><span class="mi">1</span><span class="p">]):</span>
        <span class="n">RegularPolygon</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="mi">7</span><span class="p">,</span> <span class="n">side_count</span><span class="o">=</span><span class="mi">6</span><span class="p">)</span>
        <span class="n">Circle</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="mi">4</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">)</span>
<span class="hll">    <span class="n">extrude</span><span class="p">(</span><span class="n">amount</span><span class="o">=-</span><span class="mi">2</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">)</span>
</span></pre></div>
</div>
<p>Note that <code class="docutils literal notranslate"><span class="pre">amount=-2</span></code> indicates extruding into the part and - just like
with the sketch - <code class="docutils literal notranslate"><span class="pre">mode=Mode.SUBTRACT</span></code> instructs the builder to subtract
this hexagonal shape from the part under construction.</p>
<p>At this point the part looks like:</p>
<img alt="_images/selector_before.svg" class="align-center" src="_images/selector_before.svg" />
</section>
<section id="step-6-fillet-the-top-perimeter-edge">
<h2>Step 6: Fillet the top perimeter Edge<a class="headerlink" href="#step-6-fillet-the-top-perimeter-edge" title="Link to this heading"></a></h2>
<p>The final step is to apply a fillet to the top perimeter.</p>
<div class="highlight-default notranslate"><div class="highlight"><pre><span></span><span class="kn">from</span><span class="w"> </span><span class="nn">build123d</span><span class="w"> </span><span class="kn">import</span> <span class="o">*</span>
<span class="kn">from</span><span class="w"> </span><span class="nn">ocp_vscode</span><span class="w"> </span><span class="kn">import</span> <span class="o">*</span>

<span class="k">with</span> <span class="n">BuildPart</span><span class="p">()</span> <span class="k">as</span> <span class="n">example</span><span class="p">:</span>
    <span class="n">Cylinder</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="mi">10</span><span class="p">,</span> <span class="n">height</span><span class="o">=</span><span class="mi">3</span><span class="p">)</span>
    <span class="k">with</span> <span class="n">BuildSketch</span><span class="p">(</span><span class="n">example</span><span class="o">.</span><span class="n">faces</span><span class="p">()</span><span class="o">.</span><span class="n">sort_by</span><span class="p">(</span><span class="n">Axis</span><span class="o">.</span><span class="n">Z</span><span class="p">)[</span><span class="o">-</span><span class="mi">1</span><span class="p">]):</span>
        <span class="n">RegularPolygon</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="mi">7</span><span class="p">,</span> <span class="n">side_count</span><span class="o">=</span><span class="mi">6</span><span class="p">)</span>
        <span class="n">Circle</span><span class="p">(</span><span class="n">radius</span><span class="o">=</span><span class="mi">4</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">)</span>
    <span class="n">extrude</span><span class="p">(</span><span class="n">amount</span><span class="o">=-</span><span class="mi">2</span><span class="p">,</span> <span class="n">mode</span><span class="o">=</span><span class="n">Mode</span><span class="o">.</span><span class="n">SUBTRACT</span><span class="p">)</span>
<span class="hll">    <span class="n">fillet</span><span class="p">(</span>
</span><span class="hll">        <span class="n">example</span><span class="o">.</span><span class="n">edges</span><span class="p">()</span>
</span><span class="hll">        <span class="o">.</span><span class="n">filter_by</span><span class="p">(</span><span class="n">GeomType</span><span class="o">.</span><span class="n">CIRCLE</span><span class="p">)</span>
</span><span class="hll">        <span class="o">.</span><span class="n">sort_by</span><span class="p">(</span><span class="n">SortBy</span><span class="o">.</span><span class="n">RADIUS</span><span class="p">)[</span><span class="o">-</span><span class="mi">2</span><span class="p">:]</span>
</span><span class="hll">        <span class="o">.</span><span class="n">sort_by</span><span class="p">(</span><span class="n">Axis</span><span class="o">.</span><span class="n">Z</span><span class="p">)[</span><span class="o">-</span><span class="mi">1</span><span class="p">],</span>
</span><span class="hll">        <span class="n">radius</span><span class="o">=</span><span class="mi">1</span><span class="p">,</span>
</span><span class="hll">    <span class="p">)</span>
</span>
<span class="n">show</span><span class="p">(</span><span class="n">example</span><span class="p">)</span>
</pre></div>
</div>
<p>Here we’re using the <a class="hxr-hoverxref hxr-tooltip reference internal" href="operations.html#operations_generic.fillet" title="operations_generic.fillet"><code class="xref py py-func docutils literal notranslate"><span class="pre">fillet()</span></code></a> operation which needs two things:
the edge(s) to fillet and the radius of the fillet. To provide
the edge, we’ll use more selectors as described in the following
sub-steps.</p>
<section id="step-6a-extract-all-the-edges">
<h3>Step 6a: Extract all the Edges<a class="headerlink" href="#step-6a-extract-all-the-edges" title="Link to this heading"></a></h3>
<p>Much like selecting Faces in Step 3a, we’ll select all of the <code class="docutils literal notranslate"><span class="pre">example</span></code>
part’s edges with <code class="docutils literal notranslate"><span class="pre">example.edges()</span></code>.</p>
</section>
<section id="step-6b-filter-the-edges-for-circles">
<h3>Step 6b: Filter the Edges for circles<a class="headerlink" href="#step-6b-filter-the-edges-for-circles" title="Link to this heading"></a></h3>
<p>Since we know that the edge we’re looking for is a circle, we can
filter the edges selected in Step 6a for just those that are of
geometric type <code class="docutils literal notranslate"><span class="pre">CIRCLE</span></code> with <code class="docutils literal notranslate"><span class="pre">example.edges().filter_by(GeomType.CIRCLE)</span></code>.
This step removes all of the Edges of the hexagon hole.</p>
</section>
<section id="step-6c-sort-the-circles-by-radius">
<h3>Step 6c: Sort the circles by radius<a class="headerlink" href="#step-6c-sort-the-circles-by-radius" title="Link to this heading"></a></h3>
<p>The perimeter are the largest circles - the central cylinder must be
excluded - so we’ll sort all of the circles by their radius with:
<code class="docutils literal notranslate"><span class="pre">example.edges().filter_by(GeomType.CIRCLE).sort_by(SortBy.RADIUS)</span></code>.</p>
</section>
<section id="step-6d-slice-the-list-to-get-the-two-largest">
<h3>Step 6d: Slice the list to get the two largest<a class="headerlink" href="#step-6d-slice-the-list-to-get-the-two-largest" title="Link to this heading"></a></h3>
<p>We know that the <code class="docutils literal notranslate"><span class="pre">example</span></code> part has two perimeter circles so we’ll
select just the top two edges from the sorted circle list with:
<code class="docutils literal notranslate"><span class="pre">example.edges().filter_by(GeomType.CIRCLE).sort_by(SortBy.RADIUS)[-2:]</span></code>.  The
syntax of this slicing operation is standard python list slicing.</p>
</section>
<section id="step-6e-select-the-top-edge">
<h3>Step 6e: Select the top Edge<a class="headerlink" href="#step-6e-select-the-top-edge" title="Link to this heading"></a></h3>
<p>The last sub-step is to select the top perimeter edge, the one with
the greatest Z value which we’ll do with the <code class="docutils literal notranslate"><span class="pre">sort_by(Axis.Z)[-1]</span></code> method just like
Step 3b - note that these methods work on all Shape objects (Edges, Wires,
Faces, Solids, and Compounds) - with:
<code class="docutils literal notranslate"><span class="pre">example.edges().filter_by(GeomType.CIRCLE).sort_by(SortBy.RADIUS)[-2:].sort_by(Axis.Z)[-1]</span></code>.</p>
</section>
</section>
<section id="conclusion">
<h2>Conclusion<a class="headerlink" href="#conclusion" title="Link to this heading"></a></h2>
<p>By using selectors as we have in this example we’ve used methods
of identifying features that are robust to features changing within
the part. We’ve also avoided the classic CAD “Topological naming problem”
by never referring to features with names or tags that could become obsolete
as the part changes.</p>
<p>When possible, avoid using static list indices to refer to features
extracted from methods like <code class="docutils literal notranslate"><span class="pre">edges()</span></code> as the order within the list
is not guaranteed to remain the same.</p>
</section>
</section>


           </div>
          </div>
          <footer><div class="rst-footer-buttons" role="navigation" aria-label="Footer">
        <a href="tutorial_design.html" class="btn btn-neutral float-left" title="Designing a Part in build123d" accesskey="p" rel="prev"><span class="fa fa-arrow-circle-left" aria-hidden="true"></span> Previous</a>
        <a href="tutorial_lego.html" class="btn btn-neutral float-right" title="Lego Tutorial" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right" aria-hidden="true"></span></a>
    </div>

  <hr/>

  <div role="contentinfo">
    <p>&#169; Copyright 2022, Gumyr.</p>
  </div>

  Built with <a href="https://www.sphinx-doc.org/">Sphinx</a> using a
    <a href="https://github.com/readthedocs/sphinx_rtd_theme">theme</a>
    provided by <a href="https://readthedocs.org">Read the Docs</a>.
   

</footer>
        </div>
      </div>
    </section>
  </div>
  <script>
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script> 

</body>
</html>